export const coursesList = [
  "Administração",
  "Análise e Desenvolvimento de Sistemas",
  "Artes Visuais",
  "Arquitetura e Urbanismo",
  "Biblioteconomia",
  "Ciência da Computação",
  "Ciências Biológicas",
  "Ciências Contábeis",
  "Ciências Sociais",
  "Educação Especial",
  "Bacharelado em Educação Física",
  "Licenciatura em Educação Física",
  "Ensino Religioso",
  "Empreendedorismo",
  "Engenharia Ambiental e Sanitária",
  "Engenharia Civil",
  "Engenharia de Controle e Automação",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Filosofia",
  "Física",
  "Geografia",
  "Geoprocessamento",
  "Gestão Ambiental",
  "Gestão de Cidades Inteligentes",
  "Gestão de Recursos Humanos",
  "Gestão Financeira",
  "Gestão Pública",
  "História",
  "Bacharelado em Letras-Libras",
  "Licenciatura em Letras-Libras",
  "Letras-Português",
  "Letras-Português e Espanhol",
  "Letras-Português e Inglês",
  "Logística",
  "Marketing",
  "Matemática",
  "Pedagogia",
  "Processos Gerenciais",
  "Psicopedagogia",
  "Publicidade e Propaganda",
  "Química",
  "Segurança no Trabalho",
  "Serviço Social",
  "Serviços Jurídicos e Notariais",
  "Sistemas de Telecomunicações",
  "Sistemas para Internet",
  "Sistemas de Informação",
  "Teologia",
];
